apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dronespredictions.fullname" . }}-secrets
  labels:
    {{- include "dronespredictions.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- if .Values.cloudflared.enabled }}
  CF_TUNNEL_TOKEN: {{ .Values.cloudflared.token | quote }}
  {{- end }}
